# Generated by Django 2.2.6 on 2019-10-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(max_length=7, unique=True)),
                ('creditos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeccionRamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.IntegerField()),
                ('nrc', models.IntegerField()),
                ('retiro', models.BooleanField(default=True)),
                ('ingles', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Campus')),
                ('profesores', models.ManyToManyField(to='courses.Profesor')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Ramo')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semestre')),
            ],
            options={
                'unique_together': {('ramo', 'seccion', 'semestre')},
            },
        ),
    ]
