# Generated by Django 2.2.6 on 2019-10-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191010_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='sigla',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='courses.Campus'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='profesores',
            field=models.ManyToManyField(related_name='secciones', to='courses.Profesor'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='courses.Semestre'),
        ),
        migrations.AlterUniqueTogether(
            name='ramo',
            unique_together={('nombre', 'sigla', 'creditos')},
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('year', 'semestre')},
        ),
    ]
