# Generated by Django 2.2.6 on 2019-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191011_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='nrc',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('ramo', 'seccion', 'semestre', 'nrc')},
        ),
    ]
