# Generated by Django 2.2.6 on 2019-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191011_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
