# Generated by Django 2.2.6 on 2019-10-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191011_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
