# Generated by Django 2.2.6 on 2019-10-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191011_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuposBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('disponibles', models.IntegerField()),
                ('totales', models.IntegerField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_hora', to='courses.Seccion')),
            ],
        ),
    ]
